name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install dependencies
        run: |
          uv sync --extra dev
      - name: Create wheel
        run: |
          uv build
      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: cybersec_ai
          path: dist/cybersec_ai-*-py3-none-any.whl
  create_installer:
    runs-on: ubuntu-latest
    needs: build_wheel
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: cybersec_ai
      - name: Prepare release directory
        run: |
          PACKAGE_NAME="cybersec_ai"
          WHEEL_FILE=$(find . -name 'cybersec_ai-*-py3-none-any.whl')
          mv $WHEEL_FILE "release/${WHEEL_FILE}"
          chmod +x release/install_cybersec_ai.sh

          cp config.json release/
          mv release ${PACKAGE_NAME}

          tree ${PACKAGE_NAME}/
      - name: Create release tarball
        run: |
          tar -czf cybersec_ai.tar.gz cybersec_ai
      - name: Upload release tarball
        uses: actions/upload-artifact@v4
        with:
          name: cybersec_ai_release
          path: cybersec_ai.tar.gz
  check_installer:
    runs-on: ubuntu-latest
    needs: create_installer
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Download artifact from create_installer job
        uses: actions/download-artifact@v4
        with:
          name: cybersec_ai_release
      - name: Extract release tarball
        run: |
          tar -xzf cybersec_ai.tar.gz
      - name: Run installer script
        run: |
          cd cybersec_ai
          ./install_cybersec_ai.sh

          echo "cybersec_ai/"
          ls -la

          if [ -f "install_cybersec_ai.sh" ]; then
            echo "Installer script not removed"
            exit 1
          fi

          if [ ! -d ".venv" ]; then
            echo "Virtual environment not found"
            exit 1
          fi

          if [ ! -d "logs" ]; then
            echo "Logs directory not found"
            exit 1
          fi

          if [ ! -f "config.json" ]; then
            echo "Config file not found"
            exit 1
          fi

          if [ ! -f "uninstall_cybersec_ai.sh" ]; then
            echo "Uninstallation file not found"
            exit 1
          fi

          if [ ! -f "README.txt" ]; then
            echo "README file not found"
            exit 1
          fi
